"""vote table added using autogenerate

Revision ID: 67108257ad2b
Revises: de0be4278edd
Create Date: 2025-12-27 01:30:07.139662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67108257ad2b'
down_revision: Union[str, Sequence[str], None] = 'de0be4278edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_emial_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'emial')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emial', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_emial_key'), 'users', ['emial'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'email')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.alter_column('posts', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('posts', 'content',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('posts', 'title',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_table('votes')
    # ### end Alembic commands ###
